---
title: "Examine lLife Expectancy"
author: "Ai Xiyao"
date: "2019/8/27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("gapminder")
```

# Abstract

Here, we examine the cool life expectancy plot.

#Life Expextancy Analysis

We will first clean the data

```{r}
library(gapminder)
library(tidyverse)
data("gapminder_unfiltered")
gapminder_unfiltered %>%
  group_by(year)%>%
  filter(lifeExp == max(lifeExp))%>%
  select(country, lifeExp, year)%>%
  arrange(year) ->
  sumdat
  
  

```

We will now recreate the plot from Oeppen and Vaupel(2002).


```{r}
library(ggplot2)
ggplot(sumdat, mapping = aes(x = year, y = lifeExp)) + 
  geom_point(mapping = aes(color = country)) + 
  geom_smooth(se = FALSE, method = "lm") + 
  geom_point(shape = 1) + 
  xlab("Year") + 
  ylab("Maximum Life Expectancy") + 
  theme_bw()      # 背景变白

```

```{r}
ggplot(sumdat, mapping = aes(x = year, y = lifeExp)) + 
  geom_point(mapping = aes(color = country)) + 
  geom_smooth(se = F, method = "lm") +
  theme_bw()


```

